services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    env_file:
      - ../backend/.env
    volumes:
      - ../backend/rag/faiss_index_bgem3:/app/rag/faiss_index_bgem3:ro
    ports:
      - "8001:8001"
    restart: unless-stopped

  frontend:
    build:
      context: ..
      dockerfile: docker/nginx.Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
